image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t ovski/ansible .

push:
  stage: push
  only:
    - tags
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t ovski/ansible:$CI_COMMIT_TAG --build-arg="ANSIBLE_TAG=$CI_COMMIT_TAG" .
    - docker push ovski/ansible:$CI_COMMIT_TAG
