image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  ANSIBLE_TAG: v2.7.8
  DEBIAN_TAG: stretch-20180213

build:
  stage: build
  script:
    - docker build -t ovski/ansible --build-arg="ANSIBLE_TAG=$ANSIBLE_TAG" --build-arg="DEBIAN_TAG=$DEBIAN_TAG" .

push-latest:
  stage: push
  only:
    - master
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t ovski/ansible:latest --build-arg="ANSIBLE_TAG=$ANSIBLE_TAG" --build-arg="DEBIAN_TAG=$DEBIAN_TAG" .
    - docker push ovski/ansible:latest

push-tagged:
  stage: push
  only:
    - tags
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t ovski/ansible:$ANSIBLE_TAG --build-arg="ANSIBLE_TAG=$ANSIBLE_TAG" --build-arg="DEBIAN_TAG=$DEBIAN_TAG" .
    - docker push ovski/ansible:$ANSIBLE_TAG
